export const curriculumContent = {
  badge: '4-YEAR PROGRAM',
  heading: 'CURRICULUM ROADMAP',
  description: 'A precision-engineered 8-semester journey from foundations to advanced defense.',
  semesters: [
    {
      id: 's1',
      number: 1,
      year: 1,
      label: 'Semester 1',
      phase: 'Foundation',
      subjects: [
        'Mathematics – I',
        'Programming for Problem Solving (C/C++)',
        'Digital Logic & Computer Organization Basics',
        'Introduction to Cybersecurity',
        'Engineering Physics / Electronics for Security',
        'C/C++ Programming Lab',
        'Digital Logic Lab',
        'Cybersecurity Fundamentals Lab',
      ],
    },
    {
      id: 's2',
      number: 2,
      year: 1,
      label: 'Semester 2',
      phase: 'Foundation',
      subjects: [
        'Mathematics – II',
        'Data Structures & Algorithms',
        'Computer Networks',
        'Python for Security',
        'Cryptography',
        'Cyber Law & IPR',
        'Data Structures Lab',
        'Python for Security Lab',
        'Network Fundamentals Lab',
      ],
    },
    {
      id: 's3',
      number: 3,
      year: 2,
      label: 'Semester 3',
      phase: 'Offensive Core',
      subjects: [
        'Operating Systems',
        'Database Systems & Security',
        'Discrete Mathematics',
        'Ethical Hacking (Red Team Fundamentals)',
        'Embedded Systems & Microcontrollers',
        'Operating Systems Lab',
        'Ethical Hacking Lab',
        'Embedded Systems Lab',
      ],
    },
    {
      id: 's4',
      number: 4,
      year: 2,
      label: 'Semester 4',
      phase: 'Offensive Core',
      subjects: [
        'Linux Server & Hardening',
        'Web Application Penetration Testing',
        'Wireless & Network Penetration Testing',
        'Malware Analysis',
        'IoT Architecture & Protocols',
        'Web Pentesting Lab',
        'Malware Analysis Lab',
        'Wireless Security Lab',
        'IoT Devices & Sensors Lab',
      ],
    },
    {
      id: 's5',
      number: 5,
      year: 3,
      label: 'Semester 5',
      phase: 'Hardware & Web3',
      subjects: [
        'Cloud Computing & Virtualization Security',
        'IoT Security',
        'Secure Embedded Firmware Design',
        'Smart Contract Programming (Solidity)',
        'Artificial Intelligence in Cybersecurity',
        'IoT Security Lab',
        'Smart Contract Lab',
        'Project Phase – I',
      ],
    },
    {
      id: 's6',
      number: 6,
      year: 3,
      label: 'Semester 6',
      phase: 'Hardware & Web3',
      subjects: [
        'Cyber Forensics',
        'Blockchain Fundamentals & Architecture',
        'Smart Contract Security & Auditing',
        'Mobile & API Penetration Testing',
        'Edge & Fog Security',
        'Cyber Forensics Lab',
        'Mobile/API Pentesting Lab',
        'Blockchain Security Lab',
        'Project Phase – II',
      ],
    },
    {
      id: 's7',
      number: 7,
      year: 4,
      label: 'Semester 7',
      phase: 'High-Orbit Ops',
      subjects: [
        'Cloud Security & DevSecOps',
        'Hardware Pentesting & Side-Channel Attacks',
        'AI Red Teaming & Adversarial Defense',
        'Zero Trust Architecture & GRC',
        'Decentralized Identity (DID) & Privacy Engineering',
        'Purple Team Operations & SOC Engineering',
        'Major Project – I',
      ],
    },
    {
      id: 's8',
      number: 8,
      year: 4,
      label: 'Semester 8',
      phase: 'High-Orbit Ops',
      subjects: ['Internship – II', 'Major Project – II'],
    },
  ],
} as const;
